export const APPLICATION_BOOTING = 'APPLICATION_BOOTING'
export const APPLICATION_INITIALIZED = 'APPLICATION_INITIALIZED'
export const APPLICATION_RELOAD = 'APPLICATION_RELOAD'
export const APPLICATION_NETWORK_STATUS = 'APPLICATION_NETWORK_STATUS'

export const CONNECTION_LOST = 'CONNECTION_LOST'
export const CONNECTION_ESTABLISHED = 'CONNECTION_ESTABLISHED'

export const SUPPORTBOT_ONLINE = 'SUPPORTBOT_ONLINE'

export const SET_THEME = 'SET_THEME'
export const SET_NETWORK_MODAL_OPEN = 'SET_NETWORK_MODAL_OPEN'

export const PLACE_PREDICTION = 'PLACE_PREDICTION'

export const GET_PRICE_FEED = 'GET_PRICE_FEED'
export const GET_LATEST_PRICE_FEED = 'GET_LATEST_PRICE_FEED'

export const FOCUS_ROUND = 'FOCUS_ROUND'
export const UNFOCUS_ROUND = 'UNFOCUS_ROUND'

export const TOGGLE_TOOLBAR = 'TOGGLE_TOOLBAR'

export const SET_SHOW_GAMES_LIST = 'SET_SHOW_GAMES_LIST'
export const SET_SHOW_CONNECT_BAR = 'SET_SHOW_CONNECT_BAR'
export const SET_SHOW_STATISTICS_BAR = 'SET_SHOW_STATISTICS_BAR'

export const WALLET_CONNECT = 'WALLET_CONNECT'

export const GET_GAMES = 'GET_GAMES'
export const PIN_GAME = 'PIN_GAME'
export const UNPIN_GAME = 'UNPIN_GAME'
export const SET_ACTIVE_GAME = 'SET_ACTIVE_GAME'
export const SET_GAME_LIST_FILTER_SEARCHABLE_PRICEFEED_NAMES = 'SET_GAME_LIST_FILTER_SEARCHABLE_PRICEFEED_NAMES'
export const SET_GAME_LIST_FILTER_CATEGORY = 'SET_GAME_LIST_FILTER_CATEGORY'
export const SET_GAME_LIST_FILTER_SCHEDULE = 'SET_GAME_LIST_FILTER_SCHEDULE'
export const SET_GAME_LIST_FILTER_CURRENCY = 'SET_GAME_LIST_FILTER_CURRENCY'
export const SET_GAME_LIST_FILTER_LEVEL = 'SET_GAME_LIST_FILTER_LEVEL'

export const SET_ACCOUNT = 'SET_ACCOUNT'
export const UPDATE_NICKNAME = 'UPDATE_NICKNAME'
export const RESOVLE_ADDRESS_TO_NICKNAME = 'RESOVLE_ADDRESS_TO_NICKNAME'
export const APPROVE_ACCOUNT_ALLOWANCE = 'APPROVE_ACCOUNT_ALLOWANCE'
export const GET_ALLOWANCE = 'GET_ALLOWANCE'
export const GET_BALANCE = 'GET_BALANCE'

export const GET_GAS_BALANCE = 'GET_GAS_BALANCE'

export const START_SWAP = 'START_SWAP'
export const UPDATE_SWAP = 'UPDATE_SWAP'
export const END_SWAP = 'END_SWAP'
export const SWAP_NATIVE_ERC20 = 'SWAP_NATIVE_ERC20'
export const READ_BLOCKCHAIN_SWAP_NATIVE_ERC20_POOL = 'READ_BLOCKCHAIN_SWAP_NATIVE_ERC20_POOL'
export const READ_BLOCKCHAIN_SWAP_NATIVE_ERC20_QUOTE_EX_IN = 'READ_BLOCKCHAIN_SWAP_NATIVE_ERC20_QUOTE_EX_IN'
export const READ_BLOCKCHAIN_SWAP_NATIVE_ERC20_QUOTE_EX_OUT = 'READ_BLOCKCHAIN_SWAP_NATIVE_ERC20_QUOTE_EX_OUT'

export const WITHDRAW = 'WITHDRAW'
export const RESOLVE_WITHDRAW = 'RESOLVE_WITHDRAW'
export const RESOLVE_WITHDRAW_NOCONTEST = 'RESOLVE_WITHDRAW_NOCONTEST'
export const RESOLVE = 'RESOLVE'
export const RESOLVE_NOCONTEST = 'RESOLVE_NOCONTEST'
export const JOIN_MENTOR = 'JOIN_MENTOR'

export const GET_SETTLEMENTS_BY_IDS = 'GET_SETTLEMENTS_BY_IDS'

export const SHOW_INSTALL_PROMPT = 'SHOW_INSTALL_PROMPT'

export const CHAT_CONNECTED = 'CHAT_CONNECTED'
export const CHAT_DISCONNECTED = 'CHAT_DISCONNECTED'
export const CHAT_SEND = 'CHAT_SEND'
export const CHAT_RECEIVE = 'CHAT_RECEIVE'
export const GET_CHAT_CHANNELS = 'GET_CHAT_CHANNELS'
export const GET_CHAT_CHANNEL_ONLINE = 'GET_CHAT_CHANNEL_ONLINE'
export const SET_ACTIVE_CHAT_CHENNEL = 'SET_ACTIVE_CHAT_CHENNEL'

export const AWAIT_TRANSACTION = 'AWAIT_TRANSACTION'
export const NOTIFY_ABOUT_FAILED_TRANSACTION = 'NOTIFY_ABOUT_FAILED_TRANSACTION'

export const READ_BLOCKCHAIN_PREDICTION_BY_ID = 'READ_BLOCKCHAIN_PREDICTION_BY_ID'
export const READ_BLOCKCHAIN_ROUND_BY_ID = 'READ_BLOCKCHAIN_ROUND_BY_ID'

export const READ_BLOCKCHAIN_LATEST_ROUNDS_BY_GAMEID = 'READ_BLOCKCHAIN_LATEST_ROUNDS_BY_GAMEID'
export const READ_BLOCKCHAIN_LATEST_PREDICTIONS_BY_ROUNDID = 'READ_BLOCKCHAIN_LATEST_PREDICTIONS_BY_ROUNDID'
export const READ_BLOCKCHAIN_LATEST_PREDICTIONS_BY_ADDRESS = 'READ_BLOCKCHAIN_LATEST_PREDICTIONS_BY_ADDRESS'
export const READ_BLOCKCHAIN_BLOCK_NUMBER = 'READ_BLOCKCHAIN_BLOCK_NUMBER'
export const SET_PREDICTION_PROPS_BY_ID = 'SET_PREDICTION_PROPS_BY_ID'
export const GET_BLOCKCHAIN_BETTOR_STATISTICS = 'GET_BLOCKCHAIN_BETTOR_STATISTICS'
export const GET_BLOCKCHAIN_BETTOR_JOINED_STATISTICS = 'GET_BLOCKCHAIN_BETTOR_JOINED_STATISTICS'
export const GET_BLOCKCHAIN_BETTOR_LAST_ACTIVITY_STATISTICS = 'GET_BLOCKCHAIN_BETTOR_LAST_ACTIVITY_STATISTICS'
export const GET_BLOCKCHAIN_MENTOR_STATISTICS = 'GET_BLOCKCHAIN_MENTOR_STATISTICS'
export const GET_BLOCKCHAIN_STAKER_STAKE_STATISTICS = 'GET_BLOCKCHAIN_STAKER_STAKE_STATISTICS'
export const GET_BLOCKCHAIN_STAKER_PAIDOUT_STATISTICS = 'GET_BLOCKCHAIN_STAKER_PAIDOUT_STATISTICS'
export const GET_BLOCKCHAIN_STAKER_JOINED_STATISTICS = 'GET_BLOCKCHAIN_STAKER_JOINED_STATISTICS'
export const GET_BLOCKCHAIN_STAKING_ACTUAL_EPOCH_STATISTICS = 'GET_BLOCKCHAIN_STAKING_ACTUAL_EPOCH_STATISTICS'
export const GET_BLOCKCHAIN_STAKING_ACTUAL_EPOCH_ID = 'GET_BLOCKCHAIN_STAKING_ACTUAL_EPOCH_ID'
export const GET_BLOCKCHAIN_STAKER_LAST_ACTIVITY_STATISTICS = 'GET_BLOCKCHAIN_STAKER_LAST_ACTIVITY_STATISTICS'

export const SET_LATEST_BC_BLOCK_NUMBER = 'SET_LATEST_BC_BLOCK_NUMBER'

export const TIMEFRAME_NOW_STICK = 'TIMEFRAME_NOW_STICK'
export const TIMEFRAME_NOW_UNSTICK = 'TIMEFRAME_NOW_UNSTICK'
export const TIMEFRAME_RESET = 'TIMEFRAME_RESET'

export const REQUEST_AUTHENTICATION_PSIG = 'REQUEST_AUTHENTICATION_PSIG'
export const RESET_AUTHENTICATION_PSIG = 'RESET_AUTHENTICATION_PSIG'

export const SET_CURRENCY = 'SET_CURRENCY'

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION'

export const MINT_DEMO_1000 = 'MINT_DEMO_1000'
